### ISSUE TITLE
Quarkus 3

### ISSUE THREAD

**Issue by tubbynl** [Devoxx4Kids-NPO/littil-backend#46]
mvn clean package bij mij local (`sdk use java 17.0.2-zulu`)

All javax.* prefix in the package names are changed to jakarta.*.

**Comment by tubbynl** [comment]
ik vraag mij ook een beetje af waarom dit goed gaat op de CI? @pschildkamp

**Comment by pschildkamp** [comment]
https://github.com/quarkusio/quarkus/issues/21574
Even afwachten op EE10. Daarna kunnen we over.

**Comment by tubbynl** [comment]
idd, laatste info
* https://quarkus.io/blog/our-bumpy-road-to-jakarta-ee-10/
* https://quarkus.io/blog/quarkus-3-0-0-alpha3-released/

**Comment by tubbynl** [comment]
laatste info

* https://quarkus.io/blog/quarkus-3-0-0-cr2-released/

**Comment by tubbynl** [comment]
3.0 is ondertussen wel final :)

https://quarkus.io/blog/quarkus-3-0-final-released/

**Comment by MarcelWildenburg** [comment]
#202
